// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carpark.proto

package carpark.service;

public interface AccessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carpark.AccessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idNumber = 1;</code>
   */
  java.lang.String getIdNumber();
  /**
   * <code>string idNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdNumberBytes();
}
