// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carpark.proto

package carpark.service;

public interface AvailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carpark.AvailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sumAvail = 1;</code>
   */
  int getSumAvail();
}
