// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carpark.proto

package carpark.service;

public interface AvailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carpark.AvailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isAvail = 1;</code>
   */
  boolean getIsAvail();
}
