// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carpark.proto

package carpark.service;

public interface LeaveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carpark.LeaveRequest)
    com.google.protobuf.MessageOrBuilder {
}
