// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carpark.proto

package carpark.service;

public interface SpacesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carpark.SpacesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 message = 1;</code>
   */
  int getMessage();
}
