// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carpark.proto

package carpark.service;

public interface SpacesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:carpark.SpacesRequest)
    com.google.protobuf.MessageOrBuilder {
}
