// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string documentId = 1;</code>
   */
  java.lang.String getDocumentId();
  /**
   * <code>string documentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDocumentIdBytes();
}
