// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface DocumentStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.DocumentStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string isPrinted = 1;</code>
   */
  java.lang.String getIsPrinted();
  /**
   * <code>string isPrinted = 1;</code>
   */
  com.google.protobuf.ByteString
      getIsPrintedBytes();

  /**
   * <code>string documentId = 2;</code>
   */
  java.lang.String getDocumentId();
  /**
   * <code>string documentId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDocumentIdBytes();
}
