// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface PrintRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.PrintRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string docId = 1;</code>
   */
  java.lang.String getDocId();
  /**
   * <code>string docId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDocIdBytes();
}
