// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface PrintResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.PrintResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string isPrinted = 1;</code>
   */
  java.lang.String getIsPrinted();
  /**
   * <code>string isPrinted = 1;</code>
   */
  com.google.protobuf.ByteString
      getIsPrintedBytes();

  /**
   * <code>int32 docId = 2;</code>
   */
  int getDocId();
}
