// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

/**
 * Protobuf type {@code resources.PrintResponse}
 */
public  final class PrintResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:resources.PrintResponse)
    PrintResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PrintResponse.newBuilder() to construct.
  private PrintResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PrintResponse() {
    isPrinted_ = "";
    docId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PrintResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            isPrinted_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            docId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return resources.service.ResourcesImpl.internal_static_resources_PrintResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return resources.service.ResourcesImpl.internal_static_resources_PrintResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            resources.service.PrintResponse.class, resources.service.PrintResponse.Builder.class);
  }

  public static final int ISPRINTED_FIELD_NUMBER = 1;
  private volatile java.lang.Object isPrinted_;
  /**
   * <code>string isPrinted = 1;</code>
   */
  public java.lang.String getIsPrinted() {
    java.lang.Object ref = isPrinted_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isPrinted_ = s;
      return s;
    }
  }
  /**
   * <code>string isPrinted = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIsPrintedBytes() {
    java.lang.Object ref = isPrinted_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isPrinted_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOCID_FIELD_NUMBER = 2;
  private volatile java.lang.Object docId_;
  /**
   * <code>string docId = 2;</code>
   */
  public java.lang.String getDocId() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      docId_ = s;
      return s;
    }
  }
  /**
   * <code>string docId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDocIdBytes() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      docId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIsPrintedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, isPrinted_);
    }
    if (!getDocIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, docId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIsPrintedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, isPrinted_);
    }
    if (!getDocIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, docId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof resources.service.PrintResponse)) {
      return super.equals(obj);
    }
    resources.service.PrintResponse other = (resources.service.PrintResponse) obj;

    boolean result = true;
    result = result && getIsPrinted()
        .equals(other.getIsPrinted());
    result = result && getDocId()
        .equals(other.getDocId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISPRINTED_FIELD_NUMBER;
    hash = (53 * hash) + getIsPrinted().hashCode();
    hash = (37 * hash) + DOCID_FIELD_NUMBER;
    hash = (53 * hash) + getDocId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static resources.service.PrintResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resources.service.PrintResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resources.service.PrintResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resources.service.PrintResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resources.service.PrintResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resources.service.PrintResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resources.service.PrintResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static resources.service.PrintResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static resources.service.PrintResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static resources.service.PrintResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static resources.service.PrintResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static resources.service.PrintResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(resources.service.PrintResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code resources.PrintResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:resources.PrintResponse)
      resources.service.PrintResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return resources.service.ResourcesImpl.internal_static_resources_PrintResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return resources.service.ResourcesImpl.internal_static_resources_PrintResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              resources.service.PrintResponse.class, resources.service.PrintResponse.Builder.class);
    }

    // Construct using resources.service.PrintResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isPrinted_ = "";

      docId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return resources.service.ResourcesImpl.internal_static_resources_PrintResponse_descriptor;
    }

    @java.lang.Override
    public resources.service.PrintResponse getDefaultInstanceForType() {
      return resources.service.PrintResponse.getDefaultInstance();
    }

    @java.lang.Override
    public resources.service.PrintResponse build() {
      resources.service.PrintResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public resources.service.PrintResponse buildPartial() {
      resources.service.PrintResponse result = new resources.service.PrintResponse(this);
      result.isPrinted_ = isPrinted_;
      result.docId_ = docId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof resources.service.PrintResponse) {
        return mergeFrom((resources.service.PrintResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(resources.service.PrintResponse other) {
      if (other == resources.service.PrintResponse.getDefaultInstance()) return this;
      if (!other.getIsPrinted().isEmpty()) {
        isPrinted_ = other.isPrinted_;
        onChanged();
      }
      if (!other.getDocId().isEmpty()) {
        docId_ = other.docId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      resources.service.PrintResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (resources.service.PrintResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object isPrinted_ = "";
    /**
     * <code>string isPrinted = 1;</code>
     */
    public java.lang.String getIsPrinted() {
      java.lang.Object ref = isPrinted_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isPrinted_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isPrinted = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIsPrintedBytes() {
      java.lang.Object ref = isPrinted_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isPrinted_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isPrinted = 1;</code>
     */
    public Builder setIsPrinted(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      isPrinted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string isPrinted = 1;</code>
     */
    public Builder clearIsPrinted() {
      
      isPrinted_ = getDefaultInstance().getIsPrinted();
      onChanged();
      return this;
    }
    /**
     * <code>string isPrinted = 1;</code>
     */
    public Builder setIsPrintedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      isPrinted_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object docId_ = "";
    /**
     * <code>string docId = 2;</code>
     */
    public java.lang.String getDocId() {
      java.lang.Object ref = docId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        docId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string docId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDocIdBytes() {
      java.lang.Object ref = docId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string docId = 2;</code>
     */
    public Builder setDocId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      docId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string docId = 2;</code>
     */
    public Builder clearDocId() {
      
      docId_ = getDefaultInstance().getDocId();
      onChanged();
      return this;
    }
    /**
     * <code>string docId = 2;</code>
     */
    public Builder setDocIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      docId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:resources.PrintResponse)
  }

  // @@protoc_insertion_point(class_scope:resources.PrintResponse)
  private static final resources.service.PrintResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new resources.service.PrintResponse();
  }

  public static resources.service.PrintResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PrintResponse>
      PARSER = new com.google.protobuf.AbstractParser<PrintResponse>() {
    @java.lang.Override
    public PrintResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PrintResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PrintResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PrintResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public resources.service.PrintResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

