// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface RoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.RoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomStatus = 2;</code>
   */
  java.lang.String getRoomStatus();
  /**
   * <code>string roomStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomStatusBytes();
}
