// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface RoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.RoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomNumber = 1;</code>
   */
  int getRoomNumber();
}
