// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1;</code>
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1;</code>
   */
  com.google.protobuf.ByteString
      getInputBytes();
}
