// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package resources.service;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resources.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string output = 1;</code>
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
