// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

public interface DetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.DetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 staffID = 1;</code>
   */
  int getStaffID();

  /**
   * <code>string staffFName = 2;</code>
   */
  java.lang.String getStaffFName();
  /**
   * <code>string staffFName = 2;</code>
   */
  com.google.protobuf.ByteString
      getStaffFNameBytes();

  /**
   * <code>string staffLName = 3;</code>
   */
  java.lang.String getStaffLName();
  /**
   * <code>string staffLName = 3;</code>
   */
  com.google.protobuf.ByteString
      getStaffLNameBytes();

  /**
   * <code>int32 floor = 4;</code>
   */
  int getFloor();
}
