// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

public interface DetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.DetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
