// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

/**
 * Protobuf type {@code security.DetailsRequest}
 */
public  final class DetailsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:security.DetailsRequest)
    DetailsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DetailsRequest.newBuilder() to construct.
  private DetailsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DetailsRequest() {
    staffID_ = 0;
    staffFName_ = "";
    staffLName_ = "";
    floor_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DetailsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            staffID_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            staffFName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            staffLName_ = s;
            break;
          }
          case 32: {

            floor_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return security.service.SecurityImpl.internal_static_security_DetailsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return security.service.SecurityImpl.internal_static_security_DetailsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            security.service.DetailsRequest.class, security.service.DetailsRequest.Builder.class);
  }

  public static final int STAFFID_FIELD_NUMBER = 1;
  private int staffID_;
  /**
   * <code>int32 staffID = 1;</code>
   */
  public int getStaffID() {
    return staffID_;
  }

  public static final int STAFFFNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object staffFName_;
  /**
   * <code>string staffFName = 2;</code>
   */
  public java.lang.String getStaffFName() {
    java.lang.Object ref = staffFName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      staffFName_ = s;
      return s;
    }
  }
  /**
   * <code>string staffFName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStaffFNameBytes() {
    java.lang.Object ref = staffFName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      staffFName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAFFLNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object staffLName_;
  /**
   * <code>string staffLName = 3;</code>
   */
  public java.lang.String getStaffLName() {
    java.lang.Object ref = staffLName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      staffLName_ = s;
      return s;
    }
  }
  /**
   * <code>string staffLName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStaffLNameBytes() {
    java.lang.Object ref = staffLName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      staffLName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOOR_FIELD_NUMBER = 4;
  private int floor_;
  /**
   * <code>int32 floor = 4;</code>
   */
  public int getFloor() {
    return floor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (staffID_ != 0) {
      output.writeInt32(1, staffID_);
    }
    if (!getStaffFNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, staffFName_);
    }
    if (!getStaffLNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, staffLName_);
    }
    if (floor_ != 0) {
      output.writeInt32(4, floor_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (staffID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, staffID_);
    }
    if (!getStaffFNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, staffFName_);
    }
    if (!getStaffLNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, staffLName_);
    }
    if (floor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, floor_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof security.service.DetailsRequest)) {
      return super.equals(obj);
    }
    security.service.DetailsRequest other = (security.service.DetailsRequest) obj;

    boolean result = true;
    result = result && (getStaffID()
        == other.getStaffID());
    result = result && getStaffFName()
        .equals(other.getStaffFName());
    result = result && getStaffLName()
        .equals(other.getStaffLName());
    result = result && (getFloor()
        == other.getFloor());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STAFFID_FIELD_NUMBER;
    hash = (53 * hash) + getStaffID();
    hash = (37 * hash) + STAFFFNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStaffFName().hashCode();
    hash = (37 * hash) + STAFFLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStaffLName().hashCode();
    hash = (37 * hash) + FLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getFloor();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static security.service.DetailsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static security.service.DetailsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static security.service.DetailsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static security.service.DetailsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static security.service.DetailsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static security.service.DetailsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static security.service.DetailsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static security.service.DetailsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static security.service.DetailsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static security.service.DetailsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static security.service.DetailsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static security.service.DetailsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(security.service.DetailsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code security.DetailsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:security.DetailsRequest)
      security.service.DetailsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return security.service.SecurityImpl.internal_static_security_DetailsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return security.service.SecurityImpl.internal_static_security_DetailsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              security.service.DetailsRequest.class, security.service.DetailsRequest.Builder.class);
    }

    // Construct using security.service.DetailsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      staffID_ = 0;

      staffFName_ = "";

      staffLName_ = "";

      floor_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return security.service.SecurityImpl.internal_static_security_DetailsRequest_descriptor;
    }

    @java.lang.Override
    public security.service.DetailsRequest getDefaultInstanceForType() {
      return security.service.DetailsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public security.service.DetailsRequest build() {
      security.service.DetailsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public security.service.DetailsRequest buildPartial() {
      security.service.DetailsRequest result = new security.service.DetailsRequest(this);
      result.staffID_ = staffID_;
      result.staffFName_ = staffFName_;
      result.staffLName_ = staffLName_;
      result.floor_ = floor_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof security.service.DetailsRequest) {
        return mergeFrom((security.service.DetailsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(security.service.DetailsRequest other) {
      if (other == security.service.DetailsRequest.getDefaultInstance()) return this;
      if (other.getStaffID() != 0) {
        setStaffID(other.getStaffID());
      }
      if (!other.getStaffFName().isEmpty()) {
        staffFName_ = other.staffFName_;
        onChanged();
      }
      if (!other.getStaffLName().isEmpty()) {
        staffLName_ = other.staffLName_;
        onChanged();
      }
      if (other.getFloor() != 0) {
        setFloor(other.getFloor());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      security.service.DetailsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (security.service.DetailsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int staffID_ ;
    /**
     * <code>int32 staffID = 1;</code>
     */
    public int getStaffID() {
      return staffID_;
    }
    /**
     * <code>int32 staffID = 1;</code>
     */
    public Builder setStaffID(int value) {
      
      staffID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 staffID = 1;</code>
     */
    public Builder clearStaffID() {
      
      staffID_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object staffFName_ = "";
    /**
     * <code>string staffFName = 2;</code>
     */
    public java.lang.String getStaffFName() {
      java.lang.Object ref = staffFName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        staffFName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string staffFName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStaffFNameBytes() {
      java.lang.Object ref = staffFName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staffFName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string staffFName = 2;</code>
     */
    public Builder setStaffFName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      staffFName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string staffFName = 2;</code>
     */
    public Builder clearStaffFName() {
      
      staffFName_ = getDefaultInstance().getStaffFName();
      onChanged();
      return this;
    }
    /**
     * <code>string staffFName = 2;</code>
     */
    public Builder setStaffFNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      staffFName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object staffLName_ = "";
    /**
     * <code>string staffLName = 3;</code>
     */
    public java.lang.String getStaffLName() {
      java.lang.Object ref = staffLName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        staffLName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string staffLName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStaffLNameBytes() {
      java.lang.Object ref = staffLName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staffLName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string staffLName = 3;</code>
     */
    public Builder setStaffLName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      staffLName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string staffLName = 3;</code>
     */
    public Builder clearStaffLName() {
      
      staffLName_ = getDefaultInstance().getStaffLName();
      onChanged();
      return this;
    }
    /**
     * <code>string staffLName = 3;</code>
     */
    public Builder setStaffLNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      staffLName_ = value;
      onChanged();
      return this;
    }

    private int floor_ ;
    /**
     * <code>int32 floor = 4;</code>
     */
    public int getFloor() {
      return floor_;
    }
    /**
     * <code>int32 floor = 4;</code>
     */
    public Builder setFloor(int value) {
      
      floor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 floor = 4;</code>
     */
    public Builder clearFloor() {
      
      floor_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:security.DetailsRequest)
  }

  // @@protoc_insertion_point(class_scope:security.DetailsRequest)
  private static final security.service.DetailsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new security.service.DetailsRequest();
  }

  public static security.service.DetailsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DetailsRequest>
      PARSER = new com.google.protobuf.AbstractParser<DetailsRequest>() {
    @java.lang.Override
    public DetailsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DetailsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DetailsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DetailsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public security.service.DetailsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

