// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

public interface EmUnlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.EmUnlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string codeEntered = 1;</code>
   */
  java.lang.String getCodeEntered();
  /**
   * <code>string codeEntered = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeEnteredBytes();
}
