// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

public final class SecurityImpl {
  private SecurityImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_UnlockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_UnlockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_UnlockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_UnlockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016security.proto\022\010security\"!\n\rUnlockRequ" +
      "est\022\020\n\010idNumber\030\001 \001(\t\"!\n\016UnlockResponse\022" +
      "\017\n\007message\030\001 \001(\t2U\n\020securityServices\022A\n\n" +
      "unlockDoor\022\027.security.UnlockRequest\032\030.se" +
      "curity.UnlockResponse\"\000B\"\n\020security.serv" +
      "iceB\014SecurityImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_security_UnlockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_security_UnlockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_UnlockRequest_descriptor,
        new java.lang.String[] { "IdNumber", });
    internal_static_security_UnlockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_security_UnlockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_UnlockResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
