// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

public interface UnlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.UnlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idNumber = 1;</code>
   */
  java.lang.String getIdNumber();
  /**
   * <code>string idNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdNumberBytes();
}
