// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security.service;

public interface UnlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.UnlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 codeEntered = 1;</code>
   */
  int getCodeEntered();
}
